# Generated by Django 3.2.25 on 2024-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_pin',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
