# Generated by Django 3.2.25 on 2024-09-09 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailverification_verification_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 16, 23, 27, 659169, tzinfo=utc)),
        ),
    ]
