# Generated by Django 3.2.25 on 2024-09-11 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240911_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 21, 27, 35, 544518, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='JournalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary_text', models.TextField()),
                ('suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('key_points', models.TextField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 'Not Helpful'), (2, 'Somewhat Helpful'), (3, 'Very Helpful')], null=True)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Summary',
                'verbose_name_plural': 'Journal Summaries',
            },
        ),
    ]
