# Generated by Django 3.2.25 on 2024-09-12 01:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240911_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalsummary',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='journalsummary',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 1, 39, 30, 452912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journalprompt',
            name='prompt_text',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='key_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='summary_text',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='journaltemplate',
            name='additional_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='journaltemplate',
            name='description',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='journaltopic',
            name='description',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='promptentry',
            name='user_prompt_text',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='promptentry',
            name='user_response_text',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='standaloneprompt',
            name='prompt_text',
            field=models.TextField(default=list),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=20)),
                ('text', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
        ),
    ]
