# Generated by Django 3.2.25 on 2024-09-12 03:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240912_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 3, 2, 4, 409676, tzinfo=utc)),
        ),
    ]
