# Generated by Django 3.2.25 on 2024-09-13 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalsummary',
            name='metadata',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 18, 5, 6, 198313, tzinfo=utc)),
        ),
    ]
