# Generated by Django 3.2.25 on 2024-09-13 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240913_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 19, 18, 44, 144349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journalprompt',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_prompts', to='core.journaltemplate'),
        ),
    ]
