# Generated by Django 3.2.25 on 2024-09-13 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240913_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalprompt',
            name='journal',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 19, 46, 14, 848938, tzinfo=utc)),
        ),
    ]
