# Generated by Django 3.2.25 on 2024-09-14 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240913_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 0, 4, 49, 937241, tzinfo=utc)),
        ),
    ]
