# Generated by Django 3.2.25 on 2024-09-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_emailverification_expires_at'),
        ('core', '0019_moodentry_moodresponse_moodtag'),
    ]

    operations = [
    ]
