# Generated by Django 3.2.25 on 2024-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='context',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=20),
        ),
    ]
