# Generated by Django 3.2.25 on 2024-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240916_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='cover_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
