# Generated by Django 3.2.25 on 2024-09-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('question_prompt', models.TextField()),
                ('response_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_response_time', models.FloatField(default=0)),
                ('average_session_length', models.FloatField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelconfiguration')),
            ],
        ),
    ]
