# Generated by Django 3.2.25 on 2024-10-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20240918_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalprompt',
            name='prompt_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standaloneprompt',
            name='prompt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
