# Generated by Django 3.2.25 on 2024-10-10 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20241010_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='repeats',
        ),
        migrations.RemoveField(
            model_name='goalrepetition',
            name='days_of_month',
        ),
        migrations.RemoveField(
            model_name='goalrepetition',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='goalrepetition',
            name='last_day_of_month',
        ),
        migrations.RemoveField(
            model_name='goalrepetition',
            name='repeat_type',
        ),
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='goal',
            name='repeat_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='completion_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalrepetition',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goalrepetition',
            name='repeat_on',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='goalrepetition',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repetition', to='core.goal'),
        ),
        migrations.AlterUniqueTogether(
            name='goalcompletion',
            unique_together={('goal', 'date')},
        ),
    ]
