# Generated by Django 3.2.25 on 2024-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20241010_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
